name 'dhoppe-postfix'
version '0.1.0'

author 'Dennis Hoppe'
license 'GPLv2'
project_page 'http://github.com/dhoppe/puppet-postfix'
source 'git://github.com/dhoppe/puppet-postfix'
summary 'Postfix Module'
description 'Postfix Module for Debian, Ubuntu'
dependency 'puppetlabs/stdlib', '>=0.0.1'
